language: node_js
node_js:
  - "10"
  
sudo: false

os:
  - linux

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    fi

install:
  - npm install
  - tsc -p ./ # npm run vscode:prepublish

script:
  - xvfb-run npm test --silent
